### ISSUE TITLE
Removing `:mix` from `:extra_applications`

### ISSUE THREAD

**Issue by axelson** [hrzndhrn/rewrite#43]
I recently encountered a bug which was causing our application to crash when run in release mode (although to be clear the change never made it to `prod`). It occurred because `spark` was depending on `igniter` in `MIX_ENV=prod`, and `igniter` depends on `rewrite`. Since `rewrite` includes `mix` in extra applications that was causing `mix` to be added into our release which caused a couple issues.

The direct cause of the above error was fixed in `spark` by making `igniter` optional (see https://github.com/ash-project/spark/commit/4d2d7555e7871fd90903100e1309973a9630ddfb) but I think that making a change in rewrite would make sense as well.

It may mean that if rewrite is used in an environment that doesn't include mix that it will fail. Although I think that if rewrite throws a readable exception that should be a pretty easy error to resolve for end-users.

Another option is for rewrite to only depend on mix in `MIX_ENV=dev`, using a pattern like what Phoenix does for `:inets`:
https://github.com/phoenixframework/phoenix/blob/61cbfebbd2df71e58e9edd2013047f474ab8cbc7/mix.exs#L58-L59
Although that may not work since when `rewrite` is used as a dependency, it is always compiled with `MIX_ENV=prod`.

**Comment by NickNeck** [comment]
Many thanks for the hint. I have opened an PR to clean up the `extra_appliactions`. This should solve the problem if someone accidentally sets up `rewrite` as a dependency for releases. With this approach, users will get a runtime error when calling functions from the `rewrite' package in a release. I am not sure if XXX should throw an error or a warning when someone tries to compile it in `:prod` env.

`rewrite` should never be a part of any release at all. Therefore it would be best if it is always integrated with `only: :dev`.

What was the reason to add `{:igniter, "~> 0.2 and >= 0.3.64", optional: true},` in `spark` instead of `{:igniter, "~> 0.2 and >= 0.3.64", only: :dev},`?
